(cl:in-package image_exposure_msgs-msg)
(cl:export '(EXPOSURES-VAL
          EXPOSURES
          UNDEREXPOSED-VAL
          UNDEREXPOSED
          OVEREXPOSED-VAL
          OVEREXPOSED
          MEANIRRADIANCE-VAL
          MEANIRRADIANCE
          MINMEASURABLEIRRADIANCE-VAL
          MINMEASURABLEIRRADIANCE
          MAXMEASURABLEIRRADIANCE-VAL
          MAXMEASURABLEIRRADIANCE
          MINOBSERVEDIRRADIANCE-VAL
          MINOBSERVEDIRRADIANCE
          MAXOBSERVEDIRRADIANCE-VAL
          MAXOBSERVEDIRRADIANCE
))