(cl:in-package image_exposure_msgs-msg)
(cl:export '(STAMP-VAL
          STAMP
          TIME_REFERENCE-VAL
          TIME_REFERENCE
          SHUTTERMS-VAL
          SHUTTERMS
          GAINDB-VAL
          GAINDB
          UNDEREXPOSED-VAL
          UNDEREXPOSED
          OVEREXPOSED-VAL
          OVEREXPOSED
          PIXELVAL-VAL
          PIXELVAL
          PIXELAGE-VAL
          PIXELAGE
          MEANIRRADIANCE-VAL
          MEANIRRADIANCE
          MINMEASURABLEIRRADIANCE-VAL
          MINMEASURABLEIRRADIANCE
          MAXMEASURABLEIRRADIANCE-VAL
          MAXMEASURABLEIRRADIANCE
          MINOBSERVEDIRRADIANCE-VAL
          MINOBSERVEDIRRADIANCE
          MAXOBSERVEDIRRADIANCE-VAL
          MAXOBSERVEDIRRADIANCE
))