# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from statistics_msgs/Stats1D.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Stats1D(genpy.Message):
  _md5sum = "5e29efbcd70d63a82b5ddfac24a5bc4b"
  _type = "statistics_msgs/Stats1D"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# statistics of a 1-D distribution
float64 min
float64 max 
float64 mean 
float64 variance
int64 N
"""
  __slots__ = ['min','max','mean','variance','N']
  _slot_types = ['float64','float64','float64','float64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       min,max,mean,variance,N

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Stats1D, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.min is None:
        self.min = 0.
      if self.max is None:
        self.max = 0.
      if self.mean is None:
        self.mean = 0.
      if self.variance is None:
        self.variance = 0.
      if self.N is None:
        self.N = 0
    else:
      self.min = 0.
      self.max = 0.
      self.mean = 0.
      self.variance = 0.
      self.N = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4dq().pack(_x.min, _x.max, _x.mean, _x.variance, _x.N))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.min, _x.max, _x.mean, _x.variance, _x.N,) = _get_struct_4dq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4dq().pack(_x.min, _x.max, _x.mean, _x.variance, _x.N))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.min, _x.max, _x.mean, _x.variance, _x.N,) = _get_struct_4dq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4dq = None
def _get_struct_4dq():
    global _struct_4dq
    if _struct_4dq is None:
        _struct_4dq = struct.Struct("<4dq")
    return _struct_4dq
